export const CITIES_DATA = [
  {
    name: "北京",
    lon: 116.4074,
    lat: 39.9042,
    color: "#ff0040",
    description: "中华人民共和国首都，政治、文化、国际交往中心",
    population: "2189万",
    area: "16410 km²",
    landmarks: [
      { name: "故宫博物院", desc: "世界上现存规模最大的宫殿建筑群" },
      { name: "长城", desc: "世界文化遗产，人类建筑史上的奇迹" },
      { name: "天坛", desc: "明清两代帝王祭天祈谷的场所" },
    ],
  },
  {
    name: "上海",
    lon: 121.4737,
    lat: 31.2304,
    color: "#ff8000",
    description: "中国最大的经济中心城市，国际金融中心",
    population: "2487万",
    area: "6340 km²",
    landmarks: [
      { name: "东方明珠塔", desc: "上海标志性建筑，高468米" },
      { name: "外滩", desc: "万国建筑博览群，上海近代历史缩影" },
      { name: "上海中心大厦", desc: "中国第一高楼，高632米" },
    ],
  },
  {
    name: "广州",
    lon: 113.2644,
    lat: 23.1291,
    color: "#ff8000",
    description: "华南地区最大城市，千年商都，海上丝绸之路起点",
    population: "1881万",
    area: "7434 km²",
    landmarks: [
      { name: "广州塔", desc: "昵称'小蛮腰'，高600米的地标建筑" },
      { name: "陈家祠", desc: "岭南建筑艺术明珠，清代宗祠建筑" },
      { name: "白云山", desc: "羊城第一秀，南粤名山" },
    ],
  },
  {
    name: "深圳",
    lon: 114.0579,
    lat: 22.5431,
    color: "#ff8000",
    description: "中国经济特区，全球科技创新中心之一",
    population: "1768万",
    area: "1997 km²",
    landmarks: [
      { name: "平安金融中心", desc: "深圳第一高楼，高599米" },
      { name: "世界之窗", desc: "汇集世界130多处景观的主题公园" },
      { name: "莲花山公园", desc: "邓小平铜像所在地，深圳精神象征" },
    ],
  },
  {
    name: "成都",
    lon: 104.0668,
    lat: 30.5728,
    color: "#ff8000",
    description: "天府之国，西南地区重要中心城市",
    population: "2119万",
    area: "14335 km²",
    landmarks: [
      { name: "大熊猫繁育基地", desc: "全球最大的大熊猫人工繁育机构" },
      { name: "武侯祠", desc: "中国唯一的君臣合祀祠庙" },
      { name: "锦里古街", desc: "成都最古老的商业街之一" },
    ],
  },
  {
    name: "西安",
    lon: 108.9398,
    lat: 34.3416,
    color: "#ff8000",
    description: "十三朝古都，中华文明的重要发祥地",
    population: "1295万",
    area: "10752 km²",
    landmarks: [
      { name: "秦始皇兵马俑", desc: "世界第八大奇迹" },
      { name: "大雁塔", desc: "唐代高僧玄奘主持修建的佛塔" },
      { name: "古城墙", desc: "中国现存最完整的古代城垣" },
    ],
  },
];
