// 国内主要城市数据（城市中心经纬度，用于 Cesium 飞行定位）
export const CITIES_DATA = [
  {
    name: "北京",
    lon: 116.4074,
    lat: 39.9042,
    color: "#ff0040",
    description: "中华人民共和国首都，政治、文化、国际交往中心",
    population: "2189万",
    area: "16410 km²",
    landmarks: [
      { name: "故宫博物院", desc: "世界上现存规模最大的宫殿建筑群" },
      { name: "长城", desc: "世界文化遗产，人类建筑史上的奇迹" },
      { name: "天坛", desc: "明清两代帝王祭天祈谷的场所" },
    ],
  },
  {
    name: "上海",
    lon: 121.4737,
    lat: 31.2304,
    color: "#ff8000",
    description: "中国最大的经济中心城市，国际金融中心",
    population: "2487万",
    area: "6340 km²",
    landmarks: [
      { name: "东方明珠塔", desc: "上海标志性建筑，高468米" },
      { name: "外滩", desc: "万国建筑博览群，上海近代历史缩影" },
      { name: "上海中心大厦", desc: "中国第一高楼，高632米" },
    ],
  },
  {
    name: "广州",
    lon: 113.2644,
    lat: 23.1291,
    color: "#ff8000",
    description: "华南地区最大城市，千年商都，海上丝绸之路起点",
    population: "1881万",
    area: "7434 km²",
    landmarks: [
      { name: "广州塔", desc: "昵称'小蛮腰'，高600米的地标建筑" },
      { name: "陈家祠", desc: "岭南建筑艺术明珠，清代宗祠建筑" },
      { name: "白云山", desc: "羊城第一秀，南粤名山" },
    ],
  },
  {
    name: "深圳",
    lon: 114.0579,
    lat: 22.5431,
    color: "#ff8000",
    description: "中国经济特区，全球科技创新中心之一",
    population: "1768万",
    area: "1997 km²",
    landmarks: [
      { name: "平安金融中心", desc: "深圳第一高楼，高599米" },
      { name: "世界之窗", desc: "汇集世界130多处景观的主题公园" },
      { name: "莲花山公园", desc: "邓小平铜像所在地，深圳精神象征" },
    ],
  },
  {
    name: "成都",
    lon: 104.0668,
    lat: 30.5728,
    color: "#00c8ff",
    description: "天府之国，西南地区重要中心城市",
    population: "2119万",
    area: "14335 km²",
    landmarks: [
      { name: "大熊猫繁育基地", desc: "全球最大的大熊猫人工繁育机构" },
      { name: "武侯祠", desc: "中国唯一的君臣合祀祠庙" },
      { name: "锦里古街", desc: "成都最古老的商业街之一" },
    ],
  },
  {
    name: "西安",
    lon: 108.9398,
    lat: 34.3416,
    color: "#ff8000",
    description: "十三朝古都，中华文明的重要发祥地",
    population: "1295万",
    area: "10752 km²",
    landmarks: [
      { name: "秦始皇兵马俑", desc: "世界第八大奇迹" },
      { name: "大雁塔", desc: "唐代高僧玄奘主持修建的佛塔" },
      { name: "古城墙", desc: "中国现存最完整的古代城垣" },
    ],
  },
  {
    name: "重庆",
    lon: 106.5516,
    lat: 29.5630,
    color: "#ff0040",
    description: "西南最大城市，长江上游经济中心，山城、雾都",
    population: "3213万",
    area: "82400 km²",
    landmarks: [
      { name: "洪崖洞", desc: "依山而建的吊脚楼建筑群，夜景地标" },
      { name: "解放碑", desc: "重庆中心商圈地标" },
      { name: "朝天门", desc: "长江嘉陵江交汇处，壮观两江景色" },
    ],
  },
  {
    name: "南京",
    lon: 118.7969,
    lat: 32.0603,
    color: "#00c8ff",
    description: "六朝古都，江苏省会，长三角重要中心城市",
    population: "942万",
    area: "6587 km²",
    landmarks: [
      { name: "中山陵", desc: "孙中山先生陵墓，近代建筑艺术典范" },
      { name: "明孝陵", desc: "明清皇家陵寝之首，世界文化遗产" },
      { name: "夫子庙", desc: "南京传统街市，秦淮河畔地标" },
    ],
  },
  {
    name: "武汉",
    lon: 114.3055,
    lat: 30.5928,
    color: "#00c8ff",
    description: "湖北省会，华中最大城市，长江经济带核心城市",
    population: "1364万",
    area: "8569 km²",
    landmarks: [
      { name: "黄鹤楼", desc: "江南三大名楼之一，千年文化地标" },
      { name: "东湖", desc: "中国最大的城中湖，面积是杭州西湖的6倍" },
      { name: "武汉大学", desc: "中国最美大学之一，樱花胜地" },
    ],
  },
  {
    name: "杭州",
    lon: 120.1551,
    lat: 30.2741,
    color: "#00c8ff",
    description: "浙江省会，长江三角洲中心城市，互联网之都",
    population: "1237万",
    area: "16850 km²",
    landmarks: [
      { name: "西湖", desc: "世界文化遗产，中国著名自然人文景观" },
      { name: "雷峰塔", desc: "西湖十景之一，千年古塔" },
      { name: "灵隐寺", desc: "中国佛教禅宗十大古刹之一" },
    ],
  },
  {
    name: "天津",
    lon: 117.1902,
    lat: 39.1256,
    color: "#ff8000",
    description: "环渤海经济中心，中国北方最大的港口城市",
    population: "1387万",
    area: "11966 km²",
    landmarks: [
      { name: "天津之眼", desc: "世界上唯一建在桥上的摩天轮" },
      { name: "五大道", desc: "万国建筑博览会，近代历史缩影" },
      { name: "海河", desc: "天津母亲河，夜景璀璨" },
    ],
  },
  {
    name: "苏州",
    lon: 120.5853,
    lat: 31.2989,
    color: "#00c8ff",
    description: "江南水乡古城，中国经济最强地级市，丝绸之乡",
    population: "1275万",
    area: "8657 km²",
    landmarks: [
      { name: "拙政园", desc: "中国四大名园之首，世界文化遗产" },
      { name: "苏州园林", desc: "江南园林艺术的巅峰之作" },
      { name: "平江路", desc: "800年历史的江南水街" },
    ],
  },
  {
    name: "郑州",
    lon: 113.6254,
    lat: 34.7466,
    color: "#ff8000",
    description: "河南省会，中原城市群核心，中国铁路心脏",
    population: "1282万",
    area: "7567 km²",
    landmarks: [
      { name: "二七纪念塔", desc: "郑州城市地标" },
      { name: "少林寺", desc: "禅宗祖庭，中华武术发源地" },
      { name: "黄河风景名胜区", desc: "黄河文化的重要展示地" },
    ],
  },
  {
    name: "石家庄",
    lon: 114.4793,
    lat: 38.0423,
    color: "#ff8000",
    description: "河北省会，华北重要城市，新中国摇篮",
    population: "1120万",
    area: "15848 km²",
    landmarks: [
      { name: "西柏坡", desc: "革命圣地，新中国从这里走来" },
      { name: "赵州桥", desc: "世界上现存最早的石拱桥" },
      { name: "正定古城", desc: "国家历史文化名城" },
    ],
  },
  {
    name: "济南",
    lon: 117.0009,
    lat: 36.6753,
    color: "#ff8000",
    description: "山东省会，泉城，齐鲁文化发源地",
    population: "920万",
    area: "10244 km²",
    landmarks: [
      { name: "趵突泉", desc: "天下第一泉，济南三大名胜之一" },
      { name: "大明湖", desc: "济南三大名胜，夏雨荷传说发生地" },
      { name: "千佛山", desc: "济南三大名胜，佛教名山" },
    ],
  },
  {
    name: "青岛",
    lon: 120.3826,
    lat: 36.0671,
    color: "#00c8ff",
    description: "山东半岛重要城市，红瓦绿树、碧海蓝天",
    population: "1025万",
    area: "11293 km²",
    landmarks: [
      { name: "栈桥", desc: "青岛百年地标，回澜阁所在地" },
      { name: "八大关", desc: "万国建筑博览，欧式风情街区" },
      { name: "崂山", desc: "海上第一名山，道教名山" },
    ],
  },
  {
    name: "长沙",
    lon: 112.9388,
    lat: 28.2282,
    color: "#ff8000",
    description: "湖南省会，媒体娱乐之都，长江中游重要城市",
    population: "1042万",
    area: "11819 km²",
    landmarks: [
      { name: "橘子洲", desc: "湘江中的狭长小岛，毛泽东青年艺术雕塑" },
      { name: "岳麓山", desc: "南岳衡山七十二峰之一" },
      { name: "太平街", desc: "长沙最古老的商业街，历史文化街区" },
    ],
  },
  {
    name: "大连",
    lon: 121.6147,
    lat: 38.9140,
    color: "#00c8ff",
    description: "辽东半岛最南端，辽东半岛第一大港，浪漫之都",
    population: "745万",
    area: "12573 km²",
    landmarks: [
      { name: "星海广场", desc: "亚洲最大的城市广场" },
      { name: "老虎滩海洋公园", desc: "中国最大的海洋主题公园" },
      { name: "棒棰岛", desc: "大连最美海岛度假胜地" },
    ],
  },
  {
    name: "沈阳",
    lon: 123.4315,
    lat: 41.8057,
    color: "#ff8000",
    description: "辽宁省会，东北亚重要中心城市，清朝发祥地",
    population: "912万",
    area: "12860 km²",
    landmarks: [
      { name: "沈阳故宫", desc: "清朝开国皇宫，世界文化遗产" },
      { name: "张氏帅府", desc: "北洋军阀张作霖、张学良官邸" },
      { name: "棋盘山", desc: "沈阳著名风景区和滑雪胜地" },
    ],
  },
  {
    name: "哈尔滨",
    lon: 126.6424,
    lat: 45.7560,
    color: "#00c8ff",
    description: "黑龙江省会，东北北部中心城市，冰雪之都",
    population: "988万",
    area: "53100 km²",
    landmarks: [
      { name: "哈尔滨冰雪大世界", desc: "世界最大的冰雪主题公园" },
      { name: "中央大街", desc: "百年欧式建筑风情街，东方小巴黎" },
      { name: "圣索菲亚大教堂", desc: "远东最大的东正教堂" },
    ],
  },
  {
    name: "厦门",
    lon: 118.0894,
    lat: 24.4798,
    color: "#ff8000",
    description: "福建东南沿海城市，海上花园，经济特区",
    population: "518万",
    area: "1700 km²",
    landmarks: [
      { name: "鼓浪屿", desc: "世界文化遗产，万国建筑博物馆" },
      { name: "厦门大学", desc: "中国最美大学之一，依山傍海" },
      { name: "南普陀寺", desc: "闽南佛教圣地，千年古刹" },
    ],
  },
  {
    name: "昆明",
    lon: 102.8329,
    lat: 24.8801,
    color: "#ff8000",
    description: "云南省会，春城，四季如春，面向东南亚的门户城市",
    population: "846万",
    area: "21473 km²",
    landmarks: [
      { name: "滇池", desc: "中国第六大淡水湖，高原明珠" },
      { name: "石林", desc: "世界最典型的喀斯特地貌，世界自然遗产" },
      { name: "金马碧鸡坊", desc: "昆明历史文化地标" },
    ],
  },
  {
    name: "三亚",
    lon: 109.5119,
    lat: 18.2528,
    color: "#ff8000",
    description: "海南南端热带旅游城市，东方夏威夷，国际旅游岛核心",
    population: "103万",
    area: "1921 km²",
    landmarks: [
      { name: "亚龙湾", desc: "天下第一湾，椰风海韵" },
      { name: "天涯海角", desc: "中国最南端的浪漫地标" },
      { name: "蜈支洲岛", desc: "中国第一潜水基地，海上花园" },
    ],
  },
  {
    name: "拉萨",
    lon: 91.1322,
    lat: 29.6603,
    color: "#ff8000",
    description: "西藏首府，日光城，藏传佛教圣地，海拔3650米",
    population: "55万",
    area: "29539 km²",
    landmarks: [
      { name: "布达拉宫", desc: "世界海拔最高的宫殿，世界文化遗产" },
      { name: "大昭寺", desc: "藏传佛教最神圣的寺庙，供奉释迦牟尼等身像" },
      { name: "八廓街", desc: "拉萨最古老的转经道和传统街区" },
    ],
  },
  {
    name: "乌鲁木齐",
    lon: 87.6177,
    lat: 43.8256,
    color: "#ff0040",
    description: "新疆首府，中亚区域中心，距离海洋最远的大城市",
    population: "405万",
    area: "14216 km²",
    landmarks: [
      { name: "红山公园", desc: "乌鲁木齐城市地标，俯瞰全市" },
      { name: "国际大巴扎", desc: "世界最大的巴扎（集市），西域风情" },
      { name: "天山天池", desc: "世界自然遗产，高山湖泊胜景" },
    ],
  },
  {
    name: "香港",
    lon: 114.1694,
    lat: 22.3193,
    color: "#ff0040",
    description: "国际金融中心，东方之珠，中西文化交融的国际大都市",
    population: "741万",
    area: "1106 km²",
    landmarks: [
      { name: "维多利亚港", desc: "世界三大天然良港，夜景举世闻名" },
      { name: "太平山顶", desc: "俯瞰香港全岛最佳位置" },
      { name: "迪士尼乐园", desc: "亚洲最受欢迎的主题公园之一" },
    ],
  },
  {
    name: "澳门",
    lon: 113.5439,
    lat: 22.1987,
    color: "#ff0040",
    description: "国际自由港，世界旅游休闲中心，中西文化合璧之城",
    population: "68万",
    area: "32.9 km²",
    landmarks: [
      { name: "大三巴牌坊", desc: "澳门地标，圣保禄教堂遗址" },
      { name: "威尼斯人", desc: "亚洲最大的综合性度假村和赌场" },
      { name: "澳门塔", desc: "全球十大观光塔之一，蹦极胜地" },
    ],
  },
  {
    name: "台北",
    lon: 121.5654,
    lat: 25.0330,
    color: "#ff0040",
    description: "台湾省省会，台湾政治、经济、文化中心",
    population: "260万",
    area: "271.8 km²",
    landmarks: [
      { name: "台北101", desc: "世界著名摩天大楼，台北地标" },
      { name: "故宫博物院", desc: "收藏中华国宝，世界顶级博物馆" },
      { name: "日月潭", desc: "台湾最大的天然湖泊，水沙连胜景" },
    ],
  },
  {
    name: "呼和浩特",
    lon: 111.6544,
    lat: 40.8173,
    color: "#ff8000",
    description: "内蒙古自治区首府，草原明珠，塞外青城",
    population: "344万",
    area: "17224 km²",
    landmarks: [
      { name: "大召寺", desc: "内蒙古地区重要的藏传佛教寺院" },
      { name: "昭君博物院", desc: "纪念王昭君的历史文化景区" },
      { name: "希拉穆仁草原", desc: "著名的草原旅游胜地" },
    ],
  },
  {
    name: "南宁",
    lon: 108.3200,
    lat: 22.8170,
    color: "#ff8000",
    description: "广西壮族自治区首府，中国绿城，北部湾经济区核心",
    population: "874万",
    area: "22112 km²",
    landmarks: [
      { name: "青秀山", desc: "南宁城市绿肺，国家5A级景区" },
      { name: "南湖公园", desc: "南宁最大的城市公园" },
      { name: "广西民族博物馆", desc: "展示广西各民族文化" },
    ],
  },
  {
    name: "合肥",
    lon: 117.2272,
    lat: 31.8654,
    color: "#ff8000",
    description: "安徽省会，科创之城，中国科技大学所在地",
    population: "947万",
    area: "11445 km²",
    landmarks: [
      { name: "逍遥津公园", desc: "合肥历史名园，三国古战场" },
      { name: "三河古镇", desc: "中国历史文化名镇" },
      { name: "包公园", desc: "纪念北宋名臣包拯" },
    ],
  },
  {
    name: "福州",
    lon: 119.3062,
    lat: 26.0753,
    color: "#ff8000",
    description: "福建省会，榕城，海上丝绸之路重要起点",
    population: "842万",
    area: "11968 km²",
    landmarks: [
      { name: "三坊七巷", desc: "中国十大历史文化名街" },
      { name: "鼓山", desc: "福州著名的佛教名山" },
      { name: "马尾船政遗址", desc: "中国近代海军摇篮" },
    ],
  },
  {
    name: "贵阳",
    lon: 106.7135,
    lat: 26.5784,
    color: "#ff8000",
    description: "贵州省会，避暑之都，中国大数据中心",
    population: "622万",
    area: "8034 km²",
    landmarks: [
      { name: "甲秀楼", desc: "贵阳城市地标，明代古建筑" },
      { name: "黔灵山公园", desc: "贵阳市民休闲胜地" },
      { name: "青岩古镇", desc: "贵州四大古镇之一" },
    ],
  },
  {
    name: "太原",
    lon: 112.5492,
    lat: 37.8570,
    color: "#ff8000",
    description: "山西省会，龙城，中国煤炭能源中心",
    population: "539万",
    area: "6909 km²",
    landmarks: [
      { name: "晋祠", desc: "中国现存最早的皇家祭祀园林" },
      { name: "双塔寺", desc: "太原城市地标" },
      { name: "汾河公园", desc: "太原母亲河景观带" },
    ],
  },
  {
    name: "长春",
    lon: 125.3272,
    lat: 43.8868,
    color: "#ff8000",
    description: "吉林省会，北国春城，中国汽车工业摇篮",
    population: "907万",
    area: "24744 km²",
    landmarks: [
      { name: "伪满皇宫", desc: "中国末代皇帝溥仪的宫殿" },
      { name: "净月潭", desc: "亚洲最大的人工森林" },
      { name: "长影世纪城", desc: "中国第一家电影主题公园" },
    ],
  },
  {
    name: "南昌",
    lon: 115.8921,
    lat: 28.6765,
    color: "#ff8000",
    description: "江西省会，英雄城，南昌起义发生地",
    population: "643万",
    area: "7195 km²",
    landmarks: [
      { name: "滕王阁", desc: "江南三大名楼之一" },
      { name: "八一广场", desc: "纪念南昌起义的城市中心广场" },
      { name: "鄱阳湖", desc: "中国最大淡水湖" },
    ],
  },
  {
    name: "兰州",
    lon: 103.8235,
    lat: 36.0571,
    color: "#ff8000",
    description: "甘肃省会，丝路重镇，黄河穿城而过",
    population: "436万",
    area: "13085 km²",
    landmarks: [
      { name: "中山桥", desc: "黄河第一桥" },
      { name: "白塔山", desc: "俯瞰兰州全景的名山" },
      { name: "甘肃省博物馆", desc: "收藏国宝级文物马踏飞燕" },
    ],
  },
  {
    name: "西宁",
    lon: 101.7798,
    lat: 36.6231,
    color: "#ff8000",
    description: "青海省会，夏都，青藏高原门户",
    population: "247万",
    area: "7665 km²",
    landmarks: [
      { name: "塔尔寺", desc: "藏传佛教格鲁派六大寺院之一" },
      { name: "青海湖", desc: "中国最大内陆湖" },
      { name: "东关清真大寺", desc: "西北最大清真寺之一" },
    ],
  },
  {
    name: "银川",
    lon: 106.2786,
    lat: 38.4663,
    color: "#ff8000",
    description: "宁夏回族自治区首府，塞上湖城",
    population: "289万",
    area: "9025 km²",
    landmarks: [
      { name: "镇北堡西部影城", desc: "中国电影从这里走向世界" },
      { name: "沙湖", desc: "沙水相依的独特景观" },
      { name: "西夏王陵", desc: "神秘的西夏文明遗址" },
    ],
  },
  {
    name: "海口",
    lon: 110.3312,
    lat: 20.0231,
    color: "#ff8000",
    description: "海南省省会，椰城，国际旅游岛中心城市",
    population: "290万",
    area: "3145 km²",
    landmarks: [
      { name: "骑楼老街", desc: "南洋风格的历史街区" },
      { name: "万绿园", desc: "海口最大的城市公园" },
      { name: "假日海滩", desc: "海口著名的海滨浴场" },
    ],
  },
  {
    name: "桂林",
    lon: 110.2997,
    lat: 25.2742,
    color: "#00c8ff",
    description: "广西旅游名城，桂林山水甲天下，喀斯特地貌典范",
    population: "493万",
    area: "27809 km²",
    landmarks: [
      { name: "漓江", desc: "百里山水画廊，世界自然遗产" },
      { name: "阳朔", desc: "桂林山水精华所在地，西街享誉中外" },
      { name: "象鼻山", desc: "桂林城市象征，形似大象吸水" },
    ],
  },
  {
    name: "黄山",
    lon: 118.1681,
    lat: 30.1333,
    color: "#00c8ff",
    description: "安徽南部山岳城市，黄山风景区所在地，奇松、怪石、云海、温泉",
    population: "133万",
    area: "9807 km²",
    landmarks: [
      { name: "黄山风景区", desc: "世界文化与自然双遗产，五岳归来不看山" },
      { name: "迎客松", desc: "黄山标志性松树，千年古树" },
      { name: "宏村", desc: "中国画里的乡村，徽派建筑代表" },
    ],
  },
  {
    name: "张家界",
    lon: 110.4792,
    lat: 29.1171,
    color: "#00c8ff",
    description: "湖南旅游城市，阿凡达悬浮山原型，石英砂岩峰林地貌",
    population: "152万",
    area: "9516 km²",
    landmarks: [
      { name: "天门山", desc: "世界最高天然穿山溶洞，玻璃栈道惊险刺激" },
      { name: "武陵源", desc: "世界自然遗产，三千奇峰八百秀水" },
      { name: "玻璃桥", desc: "世界最高玻璃桥，大峡谷景观" },
    ],
  },
  {
    name: "三亚湾",
    lon: 109.5000,
    lat: 18.2333,
    color: "#ff8000",
    description: "三亚最具代表性的海湾，椰梦长廊二十里",
    population: "",
    area: "",
    landmarks: [],
  },
];
