export const defaultDevelopmentFlow = {
  nodes: [
    {
      id: "product-manager",
      type: "TaskZzrw",
      x: 560,
      y: 80,
      text: "产品经理",
    },
    {
      id: "requirement-analysis",
      type: "TaskZzxd",
      x: 560,
      y: 160,
      text: "需求梳理",
    },
    {
      id: "ux-prototype",
      type: "TaskZzrw",
      x: 260,
      y: 270,
      text: "交互原型",
    },
    {
      id: "prototype-review",
      type: "TaskZzxd",
      x: 260,
      y: 370,
      text: "原型评审",
    },
    {
      id: "ui-design",
      type: "TaskZzrw",
      x: 560,
      y: 270,
      text: "UI视觉设计",
    },
    {
      id: "design-system",
      type: "TaskZzxd",
      x: 560,
      y: 370,
      text: "组件规范",
    },
    {
      id: "design-handoff",
      type: "TaskZzhd",
      x: 560,
      y: 470,
      text: "设计交付",
    },
    {
      id: "technical-review",
      type: "TaskZzhd",
      x: 860,
      y: 270,
      text: "技术评审",
    },
    {
      id: "api-design",
      type: "TaskZzxd",
      x: 860,
      y: 370,
      text: "接口设计",
    },
    {
      id: "sprint-planning",
      type: "TaskZzhd",
      x: 560,
      y: 580,
      text: "排期拆分",
    },
    {
      id: "frontend-dev",
      type: "TaskZzrw",
      x: 320,
      y: 700,
      text: "前端开发",
    },
    {
      id: "backend-dev",
      type: "TaskZzrw",
      x: 800,
      y: 700,
      text: "后端开发",
    },
    {
      id: "mock-data",
      type: "TaskZzxd",
      x: 560,
      y: 790,
      text: "Mock与联调",
    },
    {
      id: "integration",
      type: "TaskZzhd",
      x: 560,
      y: 900,
      text: "提测联调",
    },
    {
      id: "qa-test",
      type: "TaskZzxd",
      x: 560,
      y: 1010,
      text: "测试验证",
    },
    {
      id: "bugfix",
      type: "TaskZzrw",
      x: 320,
      y: 1120,
      text: "缺陷修复",
    },
    {
      id: "acceptance",
      type: "TaskZzxd",
      x: 800,
      y: 1120,
      text: "产品验收",
    },
    {
      id: "release",
      type: "TaskZzhd",
      x: 560,
      y: 1240,
      text: "上线发布",
    },
    {
      id: "review",
      type: "TaskZzxd",
      x: 560,
      y: 1340,
      text: "数据复盘",
    },
  ],
  edges: [
    {
      id: "edge-product-requirement",
      type: "bezier",
      sourceNodeId: "product-manager",
      targetNodeId: "requirement-analysis",
      text: "业务目标",
    },
    {
      id: "edge-requirement-ux",
      type: "bezier",
      sourceNodeId: "requirement-analysis",
      targetNodeId: "ux-prototype",
      text: "用户路径",
    },
    {
      id: "edge-requirement-ui",
      type: "bezier",
      sourceNodeId: "requirement-analysis",
      targetNodeId: "ui-design",
      text: "页面范围",
    },
    {
      id: "edge-requirement-tech",
      type: "bezier",
      sourceNodeId: "requirement-analysis",
      targetNodeId: "technical-review",
      text: "技术边界",
    },
    {
      id: "edge-ux-review",
      type: "bezier",
      sourceNodeId: "ux-prototype",
      targetNodeId: "prototype-review",
      text: "交互确认",
    },
    {
      id: "edge-review-design",
      type: "bezier",
      sourceNodeId: "prototype-review",
      targetNodeId: "design-handoff",
      text: "流程通过",
    },
    {
      id: "edge-ui-system",
      type: "bezier",
      sourceNodeId: "ui-design",
      targetNodeId: "design-system",
      text: "视觉规范",
    },
    {
      id: "edge-system-handoff",
      type: "bezier",
      sourceNodeId: "design-system",
      targetNodeId: "design-handoff",
      text: "标注交付",
    },
    {
      id: "edge-tech-api",
      type: "bezier",
      sourceNodeId: "technical-review",
      targetNodeId: "api-design",
      text: "接口约定",
    },
    {
      id: "edge-handoff-sprint",
      type: "bezier",
      sourceNodeId: "design-handoff",
      targetNodeId: "sprint-planning",
      text: "设计就绪",
    },
    {
      id: "edge-api-sprint",
      type: "bezier",
      sourceNodeId: "api-design",
      targetNodeId: "sprint-planning",
      text: "方案就绪",
    },
    {
      id: "edge-sprint-frontend",
      type: "bezier",
      sourceNodeId: "sprint-planning",
      targetNodeId: "frontend-dev",
      text: "页面任务",
    },
    {
      id: "edge-sprint-backend",
      type: "bezier",
      sourceNodeId: "sprint-planning",
      targetNodeId: "backend-dev",
      text: "服务任务",
    },
    {
      id: "edge-frontend-mock",
      type: "bezier",
      sourceNodeId: "frontend-dev",
      targetNodeId: "mock-data",
      text: "页面完成",
    },
    {
      id: "edge-backend-mock",
      type: "bezier",
      sourceNodeId: "backend-dev",
      targetNodeId: "mock-data",
      text: "接口完成",
    },
    {
      id: "edge-mock-integration",
      type: "bezier",
      sourceNodeId: "mock-data",
      targetNodeId: "integration",
      text: "联调通过",
    },
    {
      id: "edge-integration-qa",
      type: "bezier",
      sourceNodeId: "integration",
      targetNodeId: "qa-test",
      text: "提交测试",
    },
    {
      id: "edge-qa-bugfix",
      type: "bezier",
      sourceNodeId: "qa-test",
      targetNodeId: "bugfix",
      text: "发现问题",
    },
    {
      id: "edge-bugfix-integration",
      type: "bezier",
      sourceNodeId: "bugfix",
      targetNodeId: "integration",
      text: "回归联调",
    },
    {
      id: "edge-qa-acceptance",
      type: "bezier",
      sourceNodeId: "qa-test",
      targetNodeId: "acceptance",
      text: "测试通过",
    },
    {
      id: "edge-acceptance-release",
      type: "bezier",
      sourceNodeId: "acceptance",
      targetNodeId: "release",
      text: "验收通过",
    },
    {
      id: "edge-release-review",
      type: "bezier",
      sourceNodeId: "release",
      targetNodeId: "review",
      text: "指标观察",
    },
  ],
};
